add: logging fix: threaded bug with seq blocks in one thread

diff --git a/test/tests b/test/tests
--- a/test/tests
+++ b/test/tests
@@ -41,14 +41,14 @@ test_file() {
 
 	OUTPUT_FILE=`readlink -f "$OUTPUT_FILE"`
 	FILE=`readlink -f "$FILE"`
-	
+
 	local CMD="$HASHER $FILE "$OUTPUT_FILE" $BLOCK_SIZE $STRATEGY"
 
 
-	log "TEST[$NAME]: START"
+	log "TEST[$NAME]: START [$STRATEGY][$BLOCK_SIZE]"
 	log "$CMD"
 
-	if ! $CMD; then
+	if ! /usr/bin/time -ao "$LOG_FILE" -f"%D %K %M %e %P" $CMD; then
 		log ERROR
 		exit 1
 	fi
@@ -94,20 +94,55 @@ create_zero_file   512  "$TEMP_D/z_512"
 create_zero_file   1024 "$TEMP_D/z_1024"
 create_zero_file   100M "$TEMP_D/z_100M"
 create_random_file 100M "$TEMP_D/r_100M"
+create_random_file 1024 "$TEMP_D/r_1024"
 
-test_file "" "$TEMP_D/z_0"    512 "bf619eac0cdf3f68d496ea9344137e8b" S "$TEMP_D/z_0.S.log"
-test_file "" "$TEMP_D/z_0"    512 "bf619eac0cdf3f68d496ea9344137e8b" T "$TEMP_D/z_0.T.log"
-test_file "" "$TEMP_D/z_10"   512 "bf619eac0cdf3f68d496ea9344137e8b" S "$TEMP_D/z_10.S.log"
-test_file "" "$TEMP_D/z_10"   512 "bf619eac0cdf3f68d496ea9344137e8b" T "$TEMP_D/z_10.T.log"
-test_file "" "$TEMP_D/z_512"  512 "bf619eac0cdf3f68d496ea9344137e8b" S "$TEMP_D/z_512.S.log"
-test_file "" "$TEMP_D/z_512"  512 "bf619eac0cdf3f68d496ea9344137e8b" T "$TEMP_D/z_512.T.log"
-test_file "" "$TEMP_D/z_1024" 512 "" S "$TEMP_D/z_1024.S.log"
-test_file "" "$TEMP_D/z_1024" 512 "" T "$TEMP_D/z_1024.T.log"
-test_file "" "$TEMP_D/z_100M"   0 "" S "$TEMP_D/z_100M.S.log"
-test_file "" "$TEMP_D/z_100M"   0 "" T "$TEMP_D/z_100M.T.log"
-test_file "" "$TEMP_D/r_100M"   0 "" S "$TEMP_D/r_100M.S.log"
-test_file "" "$TEMP_D/r_100M"   0 "" T "$TEMP_D/r_100M.T.log"
-test_file "" "$TEMP_D/r_100M" 512 "" S "$TEMP_D/r_100M.S.log"
-test_file "" "$TEMP_D/r_100M" 512 "" T "$TEMP_D/r_100M.T.log"
+get_file_hash() {
+	md5sum "$1" | cut -f 1 -d" "
+}
+
+R1024_HASH=`get_file_hash "$TEMP_D/r_1024"`
+RZ512_HASH=`get_file_hash "$TEMP_D/z_512"`
+
+test_file "" "$TEMP_D/z_0"     512 "$RZ512_HASH" S "$TEMP_D/z_0.S.log"
+test_file "" "$TEMP_D/z_0"     512 "$RZ512_HASH" T "$TEMP_D/z_0.T.log"
+test_file "" "$TEMP_D/z_10"    512 "$RZ512_HASH" S "$TEMP_D/z_10.S.log"
+test_file "" "$TEMP_D/z_10"    512 "$RZ512_HASH" T "$TEMP_D/z_10.T.log"
+test_file "" "$TEMP_D/z_512"   512 "$RZ512_HASH" S "$TEMP_D/z_512.S.log"
+test_file "" "$TEMP_D/z_512"   512 "$RZ512_HASH" T "$TEMP_D/z_512.T.log"
+test_file "" "$TEMP_D/z_1024"  512 ""            S "$TEMP_D/z_1024.S.log"
+test_file "" "$TEMP_D/z_1024"  512 ""            T "$TEMP_D/z_1024.T.log"
+test_file "" "$TEMP_D/z_100M"    0 ""            S "$TEMP_D/z_100M.S.log"
+test_file "" "$TEMP_D/z_100M"    0 ""            T "$TEMP_D/z_100M.T.log"
+test_file "" "$TEMP_D/r_100M"    0 ""            S "$TEMP_D/r_100M.S.log"
+test_file "" "$TEMP_D/r_100M"    0 ""            T "$TEMP_D/r_100M.T.log"
+test_file "" "$TEMP_D/r_100M"  512 ""            S "$TEMP_D/r_100Ms.S.log"
+test_file "" "$TEMP_D/r_100M"  512 ""            T "$TEMP_D/r_100Ms.T.log"
+test_file "" "$TEMP_D/r_1024" 1024 "$R1024_HASH" S "$TEMP_D/r_1024.S.log"
+test_file "" "$TEMP_D/r_1024" 1024 "$R1024_HASH" T "$TEMP_D/r_1024.T.log"
+
+compare_same() {
+	local H1=`get_file_hash "$1"`
+	local H2=`get_file_hash "$2"`
+	if [ "$H1" != "$H2" ]; then
+		log "ERROR: files not equals: [$1] != [$2]"
+		exit 1
+	fi
+}
+
+compare_same_temp() {
+	local NAME="$1"
+	compare_same "$TEMP_D/$NAME.S.log" "$TEMP_D/$NAME.T.log"	
+}
+
+compare_same_temp "z_0"
+
+compare_same_temp "z_0"
+compare_same_temp "z_10"
+compare_same_temp "z_512"
+compare_same_temp "z_1024"
+compare_same_temp "z_100M"
+compare_same_temp "r_100M"
+compare_same_temp "r_100Ms"
+compare_same_temp "r_1024"
 
 [ -e "$DEF_OUTPUT_FILE" ] && rm "$DEF_OUTPUT_FILE"
